### ISSUE TITLE
Must click before being able to scroll

### ISSUE THREAD

**Issue by gorbypark** [rgommezz/react-native-scroll-bottom-sheet#7] opened 2020-05-25 15:20 UTC
Thanks for the amazing component, I've been extremely happy using it!  When the scroll bottom sheet is fully open, the user must click the content before being able to scroll the list.  If the user attempts to scroll before clicking, the bottom sheet itself moves.  Also, when the bottom sheet is opened half way, it's impossible to scroll the content, even with clicking first.  The user in this case must open the scroll sheet fully and then click before being able to scroll.  Is this the intended behaviour?  I've tried stripping this down (removing `<TouchableWithoutFeedback>` and the Animation handlers, etc and still the same results).
```js
    <ScrollBottomSheet
      ref={bottomBarRef}
      componentType="FlatList"
      snapPoints={[128, "50%", windowHeight - 75]}
      initialSnapIndex={2}
      onSettle={(snapIndex) =>
        setBottomBarSnapIndex([snapIndex, bottomBarSnapIndex[0]])
      }
      renderHandle={() => (
        <TouchableWithoutFeedback onPress={() => handleBottomBarClick()}>
          <View style={styles.header}>
            <View style={styles.panelHandle} />
            {bottomBarSnapIndex[0] === 2 && (
              <FadeInView duration="100">
                <View style={{ height: 50 }}>
                  <Text style={{ fontSize: 18, paddingTop: 15 }}>
                    Where do you want to go?
                  </Text>
                </View>
              </FadeInView>
            )}
            {bottomBarSnapIndex[0] >= 1 && bottomBarSnapIndex[1] === 2 && (
              <FadeOutView duration="1000">
                <View style={{ height: 50 }}>
                  <Text style={{ fontSize: 18, paddingTop: 15 }}>
                    Where do you want to go?
                  </Text>
                </View>
              </FadeOutView>
            )}
          </View>
        </TouchableWithoutFeedback>
      )}
      data={scrollListData.map((item, i) => String(item.name))}
      keyExtractor={(it) => it}
      renderItem={({ item }) => (
        <View style={styles.item}>
          <Button onPress={() => navigation.openDrawer()} title={item} />
        </View>
      )}
      contentContainerStyle={styles.contentContainerStyle}
    />
```

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.0
| react-native                      | 0.61.5
| react-native-gesture-handler      | 1.6.1
| react-native-reanimated           | 1.9.0

**Comment by djorkaeffalexandre** [comment] 2020-05-25 17:59
Is it happening only on Android devices or to at iOS devices too?

**Comment by gorbypark** [comment] 2020-05-25 19:05
@djorkaeffalexandre Sorry, I should have mentioned that I've only tested it on an iPhone as well as the iPhone simulator.  Still working on getting the android environment setup and working.

**Comment by gorbypark** [comment] 2020-05-25 19:07
![2020-05-25 21 07 11](https://user-images.githubusercontent.com/19569469/82838209-c3dfdf80-9ecb-11ea-84e4-c91a6cc9cb82.gif)

**Comment by djorkaeffalexandre** [comment] 2020-05-25 19:24
@gorbypark can you please try to give to us a reproducible at https://snack.expo.io?
It'll help a lot to find what's happening, for me it's not happening.

**Comment by gorbypark** [comment] 2020-05-25 20:23
Unfortunately it's not an expo project, so it appears I can't make a snack.  Here's the git repo if it helps, https://github.com/gorbypark/react-native-bottom-scroll

**Comment by djorkaeffalexandre** [comment] 2020-05-27 19:31
I'm facing something similar but it happens only on Android, as a temporarily fix you can use something like a visible state, that you set to false after snap to some index, so the component will unmount and mount again when you try to show.

**Comment by djorkaeffalexandre** [comment] 2020-05-28 14:56
@rgommezz can you please help us?
It's a seriously weird behavior, when we use some `setState` at the level of the `ScrollBottomSheet` component it raises a weird behavior at the scroll component and the snaps are not handled correctly.
I'm doing a reproducible snap right now.

**Comment by gorbypark** [comment] 2020-05-28 14:58
@djorkaeffalexandre I've got my android environment set up now and can confirm it's happening there as well.

**Comment by djorkaeffalexandre** [comment] 2020-05-28 15:00
@gorbypark thanks! I'm doing a minimal reproducible, then @rgommezz can see this too, I'm working right now trying to fix this issue, but my knowledge about react-native-reanimated is little.

**Comment by djorkaeffalexandre** [comment] 2020-05-28 15:14
Reproducible snack: https://snack.expo.io/@djorkaeff/react-native-scroll-bottom-sheet-issue

**Comment by djorkaeffalexandre** [comment] 2020-05-29 12:54
Another known issue that you can see on my snack is that when you just construct a new bottom sheet component and try to snapTo a intermediate point, it'll snap to the max point at Android, but the Settle prop is right. 🤔

**Comment by rgommezz** [comment] 2020-06-20 16:24
Hey guys, at the moment is not possible to change the bottom sheet configuration via state, just have to re-mount the component. See [this section](https://github.com/rgommezz/react-native-scroll-bottom-sheet#limitations) I just added. So this is most likely the main cause of all the inconsistencies you are observing.

@djorkaeffalexandre I've looked at your snack but it's contrived because I don't understand why would you need local state for what you are trying to achieve. You can have always the bottom sheet mounted on the tree and keep it hidden by setting a snap position way beyond the screen boundaries. Then you can always open it imperatively when needed.

Also, unfortunately I can't merge your PR because I don't know what use-case is solving and has the danger of easily introducing regressions on other parts. It's one of the downsides of using a complex library as reanimated, the lack of testing/shielding. I hope you understand.

This is related to https://github.com/rgommezz/react-native-scroll-bottom-sheet/issues/13 in a way and I'll treat it as duplicate since it touch bases the same underlying problem. I'll close this one and keep the other one opened for future references and in case you wanna follow up.

**Closed by rgommezz** 2020-06-20 16:24 UTC

**Comment by djorkaeffalexandre** [comment] 2020-06-20 16:28
Hey @rgommezz, thanks about your explanation.
The use case of the local state at the bottom sheet is to has a dynamically bottom sheet.
Can we have a more directly conversation at some place?
If you is available, contact me at `https://open.rocket.chat/direct/djorkaeff.alexandre` and I can try to explain the weird behavior, we're using my fix at our app and it works well.
Thanks.
